### ISSUE TITLE
webhook_url can't read from config ( Environment ) file.

### ISSUE THREAD

**Issue by rijojoseph57** [awkward/serverless-plugin-slack#3]
I found one issues while using this plugin. I was trying set webhook_url dynamically, 
the webhook_url is not fetching the values from the config file , so i debugged the plugin and analysed that the   **_this.webhook_url = this.serverless.service.custom.slack.webhook_url;_**  is reading in the constructor. So before setting up the value the constructor get executes and the webhook_url is not setting the evaluated value from config.

The Solution I found is read the webhook_url from afterDeployFunction  and afterDeployService
Add the same ( **_this.webhook_url = this.serverless.service.custom.slack.webhook_url;_** ) in this method as well.

**Developers please consider this issue when you are updating the new version**

**Comment by maartenvanvliet** [comment]
Could you file a PR?

**Comment by rijojoseph57** [comment]
I given the PR , please have a look

**Comment by rijojoseph57** [comment]
Can you have a look on my PR ,

**Comment by maartenvanvliet** [comment]
closed with https://github.com/awkward/serverless-plugin-slack/pull/4
